# Generated by Django 5.2.7 on 2026-04-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("prix", models.FloatField()),
                ("plateforme", models.CharField(max_length=100)),
                ("url", models.URLField()),
                ("date_collecte", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
