# Generated by Django 5.2.7 on 2026-04-11 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_recherche_surveillanceprix"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="Prix",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("valeur", models.FloatField()),
                ("devise", models.CharField(default="MAD", max_length=10)),
                ("plateforme", models.CharField(max_length=100)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historique_prix",
                        to="api.produit",
                    ),
                ),
            ],
        ),
    ]
