# Generated by Django 4.2.30 on 2026-04-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_produit_description_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='categorie',
            field=models.CharField(default='non_specifie', max_length=100),
        ),
    ]
