# Generated by Django 4.2.30 on 2026-05-05 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_produit_categorie'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriquePrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix', models.FloatField()),
                ('en_stock', models.BooleanField(default=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notif', models.CharField(choices=[('baisse_prix', 'Baisse de prix'), ('hausse_prix', 'Hausse de prix'), ('rupture', 'Rupture de stock'), ('retour_stock', 'Retour en stock')], max_length=20)),
                ('message', models.TextField()),
                ('ancien_prix', models.FloatField(blank=True, null=True)),
                ('nouveau_prix', models.FloatField(blank=True, null=True)),
                ('lue', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prix_au_moment', models.FloatField()),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='produit',
            name='en_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name='Prix',
        ),
        migrations.AddField(
            model_name='panier',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dans_paniers', to='api.produit'),
        ),
        migrations.AddField(
            model_name='panier',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.produit'),
        ),
        migrations.AddField(
            model_name='notification',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historiqueprix',
            name='produit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_prix', to='api.produit'),
        ),
        migrations.AlterUniqueTogether(
            name='panier',
            unique_together={('utilisateur', 'produit')},
        ),
    ]
