# Generated by Django 4.2.30 on 2026-05-06 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_historiqueprix_notification_panier_produit_en_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
